#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int t, k, m, n;
int amt,wdamt;
int accno, code;

struct BankAccount
{
    int accountNumber;
    int balance;
    int code;
    int secure;
};
struct BankAccount accounts[5];
int pointer;
void writeback();
void getinitData() // read the initial data from the text file generated by Bank program
{
    FILE *file = fopen("initdata.txt", "r");
    if (file == NULL)
    {
        perror("Error opening file");
        return;
    }
    fscanf(file, "%d %d %d %d", &t, &m, &n, &k);
    fclose(file);
    amt = t;
}
void initDisplay()
{
    printf("****************Please Enter a Card****************\n");
}
void readaccData()
{
    FILE *file = fopen("bank_data.txt", "r");
    if (file == NULL)
    {
        perror("Error opening file");
        return;
    }
    for (int i = 0; i < 5; i++)
    {
        fscanf(file, "%d,%d,%d\n", &accounts[i].accountNumber, &accounts[i].balance, &accounts[i].code);
    }
}
void cardDetails()
{
    printf("Enter card number : ");
    scanf("%d", &accno);
}
int authaccno()
{

    int flag = 0;
    for (int i = 0; i < 5; i++)
    {
        if (accno == accounts[i].accountNumber)
        {
            flag = 1;
            pointer = i;
        }
    }

    return flag;
}
int authcode()
{
    printf("Enter password code\n");
    scanf("%d", &code);
    int flag = 0;
    if (accounts[pointer].secure == 3)
    {
        printf("Card Locked ");
        exit(0);
    }

    for (int i = 0; i < 5; i++)
    {
        if (code == accounts[pointer].code)
        {
            flag = 1;
        }
    }
    return flag;
}

void txnstrt()
{
    printf("Enter the amount to withdraw : \n");
    printf("Denominations are 100    200     500\n ");
    scanf("%d",&wdamt);
    if (wdamt>amt)
    {
        printf("Not enough money in ATM");
    }
    else if(wdamt>m)
    {
        printf("Cannot withdraw more than Rs.%d per transaction\n\n",m);
    }
    else
    {
        accounts[pointer].balance -= wdamt;
        printf("Collect the money\n");
        printf("****************Reciet****************\n");
        printf("Withdraw amount     : %d\n",wdamt);
        printf("Account balance     : %d\n",accounts[pointer].balance);
        writeback();
    }
    
    
    while (1)
    {
        /* code */
    }
    
}

void writeback(){
     FILE *file = fopen("bank_data.txt", "w");
    if (file == NULL) {
        perror("Error opening file for writing");
        return;
    }

    for (int i = 0; i < 5; i++) {
        fprintf(file, "%d,%d,%d\n", accounts[i].accountNumber, accounts[i].balance, accounts[i].code);
    }

    fclose(file);
}

int main()
{

    bool authbool;
    getinitData(); // initialize Starting DATA
    while (1)
    {

        initDisplay(); // Show inital Display
        cardDetails(); // Read card number
        readaccData();
        authbool = authaccno(); // authenticate card number
        if (authbool == 0)
        {
            printf("Account not found in database\n\n\n");
        }
        else if (authbool == 1)
        {
            for (int j = 0; j < 4; j++) // need to break this loop
            {

                if (authcode() == 1)
                {
                    txnstrt();
                    break;
                }

                else
                {
                    
                    printf("Wrong code entered\n\n\n");
                    accounts[pointer].secure = j;
                }
            }
            
        }
    }
}