#include <stdio.h>
#include <stdbool.h>

#include <string.h>
#include <unistd.h>


int t, k, m, n;
int amt =t; 
int accno,code,amt;
struct BankAccount
{
    int accountNumber;
    int balance;
    int code;
};
void getData()                              // read the initial data from the text file generated by Bank program
{
    FILE *file = fopen("initdata.txt", "r");
    if (file == NULL)
    {
        perror("Error opening file");
        return;
    }
    fscanf(file, "%d %d %d %d", &t, &m, &n, &k);
    fclose(file);

}
void initDisplay(){
    printf("Please Enter a Card");
}
void cardDetails(){
    printf("Enter card number");
    scanf("%d",&accno);
}
int authaccno(){
    struct BankAccount accounts[5];
          FILE *file = fopen("bank_data.csv", "r");
    if (file == NULL)
    {
        perror("Error opening file");
        return 1;
    }
    for (int i = 0; i < 5; i++)
    {
        if (fscanf(file, "%d,%d,%d\n", &accounts[i].accountNumber, &accounts[i].balance,&accounts[i].code) == 2)
        {
            printf("Account Number: %d\n", accounts[i].accountNumber);
            printf("Balance: %d\n", accounts[i].balance);
        }
    }
    int flag = 0;
    for (int i = 0; i < 5; i++)
    {
        if (accno == accounts[i].accountNumber)
        {
            flag = 1;
        }
        
    }

    return flag;

    
}
int authcode(){
    printf("Enter password code\n");
    scanf("%d",&code);
    int flag = 0;
    for (int i = 0; i < 5; i++)
    {
        if (code == BankAccount)
        {
            
        }
        
    }
    
}


int main()
{


    






















    bool authbool;

    getData();
    initDisplay();

    cardDetails();
    authbool =  authaccno();
    if (authbool == 0)
    {
        printf("Account not found in database\n");
        return 0;
    }
    else if (authbool == 1)
    {
        authcode();

        
    }
    
    
    
 
}