#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#define RED_TEXT "\x1B[31m"
#define GREEN_TEXT "\x1B[32m"
#define RESET_TEXT "\x1B[0m"
#define BLUE_TEXT "\x1B[34m"
#define YELLOW_TEXT "\x1B[33m"

int t, k, m, n, option;
int amt, wdamt;
int accno, code;

struct BankAccount
{
    int accountNumber;
    int balance;
    int code;
    int secure;
    int lock;
    int maxperday;
};
struct BankAccount accounts[5];
int pointer;
void writeback();
void getinitData() // read the initial data from the text file generated by Bank program
{
    FILE *file = fopen("initdata.txt", "r");
    if (file == NULL)
    {
        perror("Error opening file");
        return;
    }
    fscanf(file, "%d %d %d %d", &t, &m, &n, &k);
    fclose(file);
    amt = t;
}
void initDisplay()
{
    printf(GREEN_TEXT "****************Please Enter a Card****************\n\n" RESET_TEXT);
}
void readaccData()
{
    FILE *file = fopen("bank_data.txt", "r");
    if (file == NULL)
    {
        perror("Error opening file");
        return;
    }
    for (int i = 0; i < 5; i++)
    {
        fscanf(file, "%d,%d,%d,%d,%d\n", &accounts[i].accountNumber, &accounts[i].balance, &accounts[i].code, &accounts[i].maxperday, &accounts[i].lock);
    }
}
void cardDetails()
{
    printf("Enter card number : ");
    scanf("%d", &accno);
}
int authaccno()
{

    int flag = 0;
    for (int i = 0; i < 5; i++)
    {
        if (accno == accounts[i].accountNumber)
        {
            flag = 1;
            pointer = i;
        }
    }

    return flag;
}
int authcode()
{
    printf("Enter password code\n");
    scanf("%d", &code);
    int flag = 0;

    for (int i = 0; i < 5; i++)
    {
        if (code == accounts[pointer].code)
        {
            flag = 1;
        }
    }
    return flag;
}

void txnstrt()
{
    if (accounts[pointer].lock == 0)
    {
        printf(YELLOW_TEXT "Enter the amount to withdraw : \n" RESET_TEXT);
        printf(YELLOW_TEXT "Denominations are   100    200     500\n" RESET_TEXT);
        scanf("%d", &wdamt);

        if (wdamt > amt)
        {
            printf(RED_TEXT "Not enough money in ATM\n\n" RESET_TEXT);
            txnstrt();
        }
        else if (wdamt > m)
        {
            printf(RED_TEXT "Cannot withdraw more than Rs.%d per transaction\n\n" RESET_TEXT, m);
            txnstrt();
        }
        else
        {
            if (accounts[pointer].balance > wdamt)
            {

                if (wdamt % 500 == 0 || wdamt % 100 == 0 || wdamt % 200 == 0)
                {
                    if (wdamt < accounts[pointer].maxperday)
                    {

                        accounts[pointer].balance -= wdamt;
                        accounts[pointer].maxperday -= wdamt;
                        printf(GREEN_TEXT "\n\n****************Processing*****************\n\n" RESET_TEXT);
                        for (int i = 0; i < 1000000; i++)
                        {
                            for (int i = 0; i < 1000; i++)
                            {
                                /* code */
                            }
                        }

                        printf(YELLOW_TEXT "Collect the money\n\n" RESET_TEXT);
                        printf(GREEN_TEXT "******************Reciet******************\n" RESET_TEXT);
                        printf("Withdraw amount                 : %d\n", wdamt);
                        printf("Account balance                 : %d\n", accounts[pointer].balance);
                        printf("Today's transaction amount left  : %d\n", accounts[pointer].maxperday);
                        printf(GREEN_TEXT "******************************************\n" RESET_TEXT);
                        writeback();
                    }
                    else
                    {
                        printf(RED_TEXT "Withdraw amount exceeds max withdraw perday" RESET_TEXT);
                    }
                }
                else
                {
                    printf(RED_TEXT "Enter withdrawl amount according to the denomination available\n\n" RESET_TEXT);
                    txnstrt();
                }
            }
            else
            {
                printf(RED_TEXT "Not enough balance" RESET_TEXT);
            }
        }

        while (1)
        {
            /* code */
        }
    }
    else
    {
        printf(RED_TEXT "The Card is locked for entering wrong code multiple times\n\n" RESET_TEXT);
    }
}

void writeback()
{
    FILE *file = fopen("bank_data.txt", "w");
    if (file == NULL)
    {
        perror("Error opening file for writing");
        return;
    }

    for (int i = 0; i < 5; i++)
    {
        fprintf(file, "%d,%d,%d,%d,%d\n", accounts[i].accountNumber, accounts[i].balance, accounts[i].code, accounts[i].maxperday, accounts[i].lock);
    }

    fclose(file);
    FILE *file1 = fopen("logfile.txt", "a"); // Open "logfile.txt" in append mode
    if (file1 == NULL)
    {
        perror("Error opening log file for writing");
        return;
    }
    time_t rawtime;
    struct tm *timeinfo;
    time(&rawtime);
    timeinfo = localtime(&rawtime);
    char timestamp[50];
    strftime(timestamp, sizeof(timestamp), "%Y-%m-%d %H:%M:%S", timeinfo);
    fprintf(file1, "Account number : %d  Transaction Amount : %d     ", accounts[pointer].accountNumber, wdamt);
    fprintf(file1, "Transaction time: %s\n", timestamp);

    fclose(file1);
}

void reccall(){
    printf(GREEN_TEXT "******************Select an operation to perform*****************\n\n" RESET_TEXT);
                        printf(YELLOW_TEXT "        1:    Withdraw Money\n        2:    Check Balance\n        3:    Print Balance Receit\n        4:    Exit\n\n" RESET_TEXT);
                        printf(GREEN_TEXT "******************************************************************\n\n" RESET_TEXT);
                        scanf("%d", &option);
                        switch (option)
                        {
                        case 1:
                            txnstrt();
                            break;

                        case 2:
                            printf("The available balance is %d\n\n", accounts[pointer].balance);
                            reccall();
                            break;

                        case 3:
                            printf(GREEN_TEXT "****************Receit**************** \n\n\n" RESET_TEXT);
                            printf("Account Number      :   %d\n", accounts[pointer].accountNumber);
                            printf("Account Balance     :   %d\n", accounts[pointer].balance);
                            printf("Today's transaction amount left  :%d\n", accounts[pointer].maxperday);

                            printf(GREEN_TEXT "\n\n\n************************************** \n\n\n" RESET_TEXT);
                            reccall();
                        default:

                            break;
                        }

};

int main()
{

    bool authbool;
    getinitData(); // initialize Starting DATA
    while (1)
    {

        initDisplay(); // Show inital Display
        cardDetails(); // Read card number
        readaccData();
        authbool = authaccno(); // authenticate card number
        if (authbool == 0)
        {
            printf(RED_TEXT "Account not found in database\n\n\n" RESET_TEXT);
        }
        else if (authbool == 1)
        {
            int x = 2;
            for (int j = 1; j <= 3; j++) // need to break this loop
            {
                int code = authcode();
                if (code == 1)
                {
                   
                        reccall();
                        break;
                    }
                
                else if (code == 0)
                {

                    printf(RED_TEXT "Wrong code entered\n\n\n" RESET_TEXT);
                    printf("You've %d chances left \n", x);
                    x = x - 1;
                    accounts[pointer].secure = j;
                    if (accounts[pointer].secure == 3)
                    {
                        accounts[pointer].lock = 1;
                        printf(RED_TEXT "Card Locked " RESET_TEXT "\n");
                        writeback();
                        while (1)
                        {
                        }

                        exit(0);
                    }
                }
            }
        }
    }
}